using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerControl : MonoBehaviour
{
    [SerializeField] Transform level;
    [SerializeField][Range(0,1)] float Sensetive;
    Vector3 _previevMousePos;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
#if UNITY_EDITOR
        if (Input.GetMouseButton(0))
        {
            Vector3 delta = Input.mousePosition - _previevMousePos;
            level.Rotate(0, -delta.x * Sensetive, 0);
        }
        _previevMousePos = Input.mousePosition;
#else

#endif
    }
}
